MarshallAsch/veil-droid

app/src/main/AndroidManifest.xml

added auto adjust for layouts to account for soft keyboard

---

app/src/androidTest/java/ca/marshallasch/veil/database/DatabaseTest.java
app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/java/ca/marshallasch/veil/database/Database.java
app/src/main/java/ca/marshallasch/veil/database/Migrations.java
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_signup.xml
app/src/main/res/values/strings.xml

closes #25 user accounts are now added to the database when signing up and login now checks against the database.
Login and sign up now work.
also added a database migration class.

25 Account Logic

---

app/src/main/AndroidManifest.xml
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/res/drawable/launch_screen.xml
app/src/main/res/values/styles.xml

closes #6 .  I would like to add the app name to it as well, but its not necessary.

Added a basic splash screen

---

app/src/main/java/ca/marshallasch/veil/ForumStorage.java

Added the interface for the data storage. This is the interface that will be used for all the nodes to access the communal set of data records that is independent of an underlying implementation of how the data will be stored.
closes #31.
Can you also review if the interface makes sense or if it is missing any needed functionality.

31 data storage interface creation

---

app/src/main/java/ca/marshallasch/veil/FragmentLogin.java

Fixed. removed the line where it navigated to the dash fragment regardless of the credentials entered.
This fixes #34

34 Login  hotfix

---

app/src/main/java/ca/marshallasch/veil/ForumStorage.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/java/ca/marshallasch/veil/MemoryStore.java
app/src/main/java/ca/marshallasch/veil/exceptions/TooManyResultsException.java
app/src/main/java/ca/marshallasch/veil/utilities/Util.java
app/src/main/proto/dht.proto

closes #40 . Basic implementation of a local data store has been completed, Note that it is not 100% finished, the function `updateUser(DhtProto.User user);`  has not been implemented yet and is left as a stub that returns `false`. This should allow most of the app functionality to be mocked on a single device then adding in RM to share between devices should be easy after that.

40 in memory data store

---

app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/FragmentLanding.java
app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java

closes #43 Changed all `android.app.Fragment` classes to `android.support.v4.appFragment`

43 fragment support migration

---

app/src/main/java/ca/marshallasch/veil/DataStore.java
app/src/main/java/ca/marshallasch/veil/ForumStorage.java
app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
app/src/main/java/ca/marshallasch/veil/HashTableStore.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
app/src/main/java/ca/marshallasch/veil/database/Database.java
app/src/main/java/ca/marshallasch/veil/utilities/Util.java
app/src/main/proto/sync.proto
app/src/main/res/values/strings.xml
app/src/test/java/ca/marshallasch/veil/HashTableStoreTest.java

closes #47 moved the data access into a wrapper class. started adding in data sync messages

47 delegate data store

---

app/build.gradle

closes #63 updated RightMesh version.

63 updated RM version

---

app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
app/src/main/java/ca/marshallasch/veil/FragmentLanding.java
app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/java/ca/marshallasch/veil/database/Database.java
app/src/main/java/ca/marshallasch/veil/utilities/Util.java
app/src/main/res/layout/fragment_login.xml
app/src/main/res/values/strings.xml

closes #65. Added the ability to remember the username and password to keep the user logged in. 
Note that it will continue to remember even after the device restarts which we might want to change.

65 remember login

---

app/build.gradle
app/src/main/java/ca/marshallasch/veil/FragmentAddComment.java
app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/FragmentLanding.java
app/src/main/java/ca/marshallasch/veil/FragmentPeerList.java
app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java

closes #70. Added up navigation to the app to be able to navigate with ether the back button on the up button on the app bar.
***Note:*** Be carful about the changes to the application level build.gradle file which had changes in both master and in this branch.

70 up navigation

---

app/src/main/java/ca/marshallasch/veil/FragmentDashBoard.java
app/src/main/java/ca/marshallasch/veil/FragmentLanding.java
app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
app/src/main/res/layout/fragment_landing.xml
app/src/main/res/layout/fragment_login.xml

landing page refactor + moved around items in login page

---

app/src/main/java/ca/marshallasch/veil/CommentListAdapter.java
app/src/main/java/ca/marshallasch/veil/DataStore.java
app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
app/src/main/java/ca/marshallasch/veil/comparators/PostComparator.java
app/src/main/res/layout/fragment_account_management.xml
app/src/main/res/layout/list_cell.xml
app/src/main/res/layout/post_list_cell.xml
app/src/main/res/values/strings.xml
app/src/test/java/ca/marshallasch/veil/comparators/PostComparatorTest.java

closes #101 
- sort the post list before displaying it
- added the author name and the age to the post list
- the comment count on the post list now works

101 update post display

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/FragmentPeerList.java
app/src/main/java/ca/marshallasch/veil/HashTableStore.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/java/ca/marshallasch/veil/controllers/RightMeshController.java
app/src/main/java/ca/marshallasch/veil/database/Database.java
app/src/main/java/ca/marshallasch/veil/services/VeilService.java
app/src/main/res/values/strings.xml

94 rightmesh service

---

app/src/main/java/ca/marshallasch/veil/FragmentAddComment.java
app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/FragmentPeerList.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/java/ca/marshallasch/veil/controllers/RightMeshController.java
app/src/main/java/ca/marshallasch/veil/services/VeilService.java

This is now fixed to work with the service, Something went wrong before and not everything got committed.

Hotfix #60, Not all changes were included. 

---

app/src/main/java/ca/marshallasch/veil/FragmentPeerList.java
app/src/main/java/ca/marshallasch/veil/controllers/RightMeshController.java
app/src/main/java/ca/marshallasch/veil/services/VeilService.java

closes #110.  Added some fixes to the comments to fix invalid javadoc comment tags, also made the RightMeshController be instantiated before the message thread so that it will exist before any messages are handled.

110 NullPointerException in RightMesh Service

---

.idea/assetWizardSettings.xml
app/src/main/java/ca/marshallasch/veil/DataStore.java
app/src/main/java/ca/marshallasch/veil/FragmentViewPost.java
app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
app/src/main/java/ca/marshallasch/veil/database/Database.java
app/src/main/java/ca/marshallasch/veil/database/KnownPostsContract.java
app/src/main/java/ca/marshallasch/veil/database/Migrations.java
app/src/main/res/drawable/unread_icon.xml
app/src/main/res/layout/post_list_cell.xml

closes #100. Adds in unread markers to the post list that will go away after a post is looked at.

100 read markers

---

app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java

Fixes #87. Added `AsyncTasks` to move some of the datastore work off of the main UI thread to reduce the number of frame skips.

87 offload work from ui thread

---

app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_signup.xml

closes #114. Added the loading spinner to the login and the sign up page.

114 Loading Spinner

---

app/src/main/java/ca/marshallasch/veil/DataStore.java
app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
app/src/main/java/ca/marshallasch/veil/comparators/PostAgeComparator.java
app/src/main/java/ca/marshallasch/veil/comparators/PostAuthorComparator.java
app/src/main/java/ca/marshallasch/veil/comparators/PostTitleComparator.java
app/src/main/java/ca/marshallasch/veil/database/Migrations.java
app/src/main/res/layout/fragment_discover_forums.xml
app/src/main/res/layout/fragment_login.xml
app/src/main/res/menu/sort_menu.xml
app/src/main/res/values/strings.xml
app/src/test/java/ca/marshallasch/veil/comparators/PostAgeComparatorTest.java
app/src/test/java/ca/marshallasch/veil/comparators/PostAuthorComparatorTest.java
app/src/test/java/ca/marshallasch/veil/comparators/PostTitleComparatorTest.java

closes #102. Adds the ability to sort the list of posts. 
6 options:
- Title ascending
- Title descending
- Author name ascending
- Author name descending
- Date posted newest first
- Date posted oldest first.

102 sort posts

---

app/src/androidTest/java/ca/marshallasch/veil/MainUITest.java
app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
app/src/main/java/ca/marshallasch/veil/tagList/ListState.java
app/src/main/java/ca/marshallasch/veil/tagList/TagListAdapter.java
app/src/main/res/layout/fragment_create_post.xml
app/src/main/res/layout/tag_list_item.xml
app/src/main/res/values/strings.xml

closes #104. Added in a fixed tag list instead of a free text field to add a bit more consistency and structure. The actual list of tags needs to be figured out still.

104 hardcoded tag list

---

app/src/main/java/ca/marshallasch/veil/FragmentAddComment.java
app/src/main/java/ca/marshallasch/veil/FragmentChangePassword.java
app/src/main/java/ca/marshallasch/veil/FragmentCreatePost.java
app/src/main/java/ca/marshallasch/veil/FragmentLogin.java
app/src/main/java/ca/marshallasch/veil/FragmentSignUp.java
app/src/main/java/ca/marshallasch/veil/utilities/Util.java

closes #121. Bug fix the up navigation back button will now hide the keyboard.

121 keyboard not hiding

---

app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
app/src/main/res/layout/fragment_discover_forums.xml
app/src/main/res/values/strings.xml

closes #118. Adds the ability to filter by the tags that were added to the posts from #104.

118 filter by tags

---

app/src/main/java/ca/marshallasch/veil/HashTableStore.java

Closes #132. Added a if null check to prevent the exception.

132 Null Pointer Exception in the hashTableStore

---

.idea/kotlinc.xml
app/src/main/AndroidManifest.xml

closes #128. Locks the app to portrait. Do some research into handling screen rotation without crashing.

128 Lock Portrait

---

.idea/kotlinc.xml
app/src/main/java/ca/marshallasch/veil/DataStore.java
app/src/main/java/ca/marshallasch/veil/FragmentDiscoverForums.java
app/src/main/java/ca/marshallasch/veil/HashTableStore.java
app/src/main/java/ca/marshallasch/veil/MainActivity.java
app/src/main/java/ca/marshallasch/veil/PostListAdapter.java
app/src/main/java/ca/marshallasch/veil/controllers/RightMeshController.java

closes #120. closes #134. Reduces the the data lost when the device crashes by more frequently saving the data store to a file. Various other small fixes.

120 loosing data when crashes

---

app/src/main/java/ca/marshallasch/veil/PostListAdapter.java

closes #141. Fixed the author name showing up in the post list when it should be anonymous.

141 anonymous post bugs

---

app/src/main/res/layout/fragment_login.xml

closes #145. Improved the buttons covering the input fields on the login page, however it is a trade off between that and having the buttons jump.
I found that on different devices the buttons now "jump up" from the dash page.

145 login page buttons

---

app/src/main/java/ca/marshallasch/veil/FragmentSettings.java
app/src/main/java/ca/marshallasch/veil/controllers/RightMeshController.java

closes #142. Setting the notification for new posts and new comments now works,
some small bug fix where the new comment message does not get handles properly

142 enable notification settings

---

app/build.gradle

closes #154. updated gradle versions

154 Update RightMesh 0.9.0
